INSERT INTO burger (id, burger_name) VALUES (1, 'Shroom');
INSERT INTO burger (id, burger_name, devoured) VALUES (2, 'Anything Goes', true);
INSERT INTO burger (id, burger_name) VALUES (3, 'Deluxe');
INSERT INTO burger (id, burger_name) VALUES (4, 'Bacon Burger');
INSERT INTO burger (id, burger_name) VALUES (5, 'Vegan');
INSERT INTO burger (id, burger_name) VALUES (6, 'Any BurgerYour Way');
INSERT INTO burger (id, burger_name, devoured) VALUES (7, 'Healthy Deluxe', true);
INSERT INTO burger (id, burger_name) VALUES (8, 'Crab Burger');
INSERT INTO burger (id, burger_name) VALUES (9, 'Top Burger Extra Cheese');
INSERT INTO burger (id, burger_name) VALUES (10, 'Turkey Burger');
INSERT INTO burger (id, burger_name, devoured) VALUES (11, 'Bottomless Burger', true);
